version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: booker_mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./books.sql:/docker-entrypoint-initdb.d/books.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - booker_network

  php:
    build: .
    container_name: booker_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql
    networks:
      - booker_network
    environment:
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8

networks:
  booker_network:
    driver: bridge

volumes:
  mysql_data:
